run:
  timeout: '5m'

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - gocyclo
    - exhaustive
    - typecheck
    - asciicheck
    #- errorlint" # disbale it for now, because the error style seems inconsistent with the one required by the linter
    - revive
    - exhaustruct

linters-settings:
  revive:
    ignore-generated-header: false
    severity: warning
    confidence: 3
  exhaustruct:
    include:
      - 'github.com.CeresDB.ceresmeta.*'
