etcd-start-timeout-ms = 30000
peer-urls = "http://{HostIP2}:22380"
advertise-client-urls = "http://{HostIP2}:22379"
advertise-peer-urls = "http://{HostIP2}:22380"
client-urls = "http://{HostIP2}:22379"
wal-dir = "/tmp/ceresmeta2/wal"
data-dir = "/tmp/ceresmeta2/data"
node-name = "meta2"
initial-cluster = "meta0=http://{HostIP0}:2380,meta1=http://{HostIP1}:12380,meta2=http://{HostIP2}:22380"
default-cluster-node-count = 2
default-http-port = 8080

[etcd-log]
file = "/tmp/ceresmeta2/etcd.log"
